name: json_rest_server
description: A RESTful server based on JSON With this package you can have a fully functional RESTful server with auth, pagination and all the necessaries services do build an application
version: 1.6.0
repository: https://github.com/rodrigorahman/json_rest_server
issue_tracker: https://github.com/rodrigorahman/json_rest_server/issues

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  args: ^2.3.1
  event_bus: ^2.0.0
  get_it: ^7.2.0
  http: ^0.13.5
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  path: ^1.8.2
  shelf: ^1.3.2
  shelf_multipart: ^1.0.0
  shelf_static: ^1.1.1
  uuid: ^4.2.1  
  yaml: ^3.1.1

dev_dependencies:
  dio: ^5.1.1
  lints: ^2.0.0
  test: ^1.24.3

dependency_overrides: 
  analyzer: 5.13.0
  watcher: 1.1.0
  pub_semver: 2.1.4

executables:
  json_rest_server: json_rest_server
  jsonRestServer: json_rest_server
  jrs: json_rest_server

