name: Json Rest Server
port: 8080
host: 0.0.0.0
database: database.json

# storage:
#   folder: storage/
#   name: "file"

auth:
  jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
  jwtExpire: 3600
  unauthorizedStatusCode: 403
  urlSkip:
#     - products
